OpenNMT/Tokenizer

CHANGELOG.md
include/onmt/ITokenizer.h
include/onmt/SpaceTokenizer.h
include/onmt/Tokenizer.h
src/SpaceTokenizer.cc
src/Tokenizer.cc
test/test.cc

keep count of the type of each character discovered during tokenization - will not work for space tokenization not parsing the actual string.

Return discovered alphabets while tokenizing

---

CHANGELOG.md
bindings/python/Python.cc
bindings/python/README.md
cli/tokenize.cc
docs/options.md
include/onmt/AnnotatedToken.h
include/onmt/CaseModifier.h
include/onmt/SubwordEncoder.h
include/onmt/Tokenizer.h
src/AnnotatedToken.cc
src/CaseModifier.cc
src/SentencePiece.cc
src/SubwordEncoder.cc
src/Tokenizer.cc
test/test.cc

This PR adds a new `case_markup` option that injects case information as additional token and lowercases the input. The possible injected tokens are:
* `｟case_modifier_C｠`: capitalize the next token
* `｟case_modifier_U｠`: uppercase the next token
* `｟begin_case_region_U｠`: start an uppercase region
* `｟end_case_region_U｠`: terminate an uppercase region
Case regions are required when subword encoders is used. Otherwise 2 issues can arise:
1. Ambiguous detokenization:
* With subword: `WORLD` -> `｟case_modifier_U｠ wo￭ rld`
* Without subword: `WOrld` -> `｟case_modifier_U｠ wo￭ rld`
2. Subword sequence inconsistent with other cases:
* With subword: `WORLD` -> `｟case_modifier_U｠ wo￭ ｟case_modifier_U｠ rld`
* With subword: `world` -> `wo￭ rld`
Thus, it has been proposed to use opening and closing …

Add option to inject case information as new tokens

---

include/onmt/unicode/Unicode.h
src/BPE.cc
src/BPELearner.cc
src/Tokenizer.cc
src/unicode/Unicode.cc

this PR is to fix slowdown introduced in #59 and is separating structure from main code point and the structure from combining marks that was causing the overhead.
In my benchmark, performance is now on par with before #59 - can you please double-check?
We can push the idea a bit further and obtain a slight performance improvement from baseline when separating completely the 2 functions `explode_utf8_with_marks` - but this would make maintenance more complicated.

Optim tokbpe with combining

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py

Allow naming positional arguments in the Python API

---

include/onmt/AnnotatedToken.h
include/onmt/BPELearner.h
include/onmt/SPMLearner.h
include/onmt/SubwordLearner.h
include/onmt/Tokenizer.h
src/AnnotatedToken.cc
src/BPELearner.cc
src/SPMLearner.cc
src/SubwordEncoder.cc
src/SubwordLearner.cc
src/Tokenizer.cc

The current methods can only return the final token string representation which for example includes joiner and spacers. It is sometimes useful to get the intermediate annotated representation instead. Typically subword learning should ignore joiners/spacers and the current approach to call `unset_annotate` was a bit hacky.

Add method to get the annotated token representation

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py
cli/detokenize.cc
cli/tokenize.cc
include/onmt/ITokenizer.h
src/ITokenizer.cc

This PR moves the stream processing API inside the library and adds threading support for tokenization. Detokenization will remain sequential as it is mostly I/O bound.
Closes #71.

Add threading to stream tokenization

---

bindings/python/Python.cc
bindings/python/README.md
cli/tokenize.cc
docs/options.md
include/onmt/Tokenizer.h
src/Tokenizer.cc
test/test.cc

implement new tokenisation option allowing to support joiners present in input string. This is interesting to combine multiple tokenization - or performed a pre-tokenization with a pre-process.
The PR also fix substitution of special characters that was not performed for `space` tokenization mode.

Support prior joiners

---

include/onmt/Tokenizer.h
src/Tokenizer.cc
test/test.cc

@jsenellart, FYI about this regression.
I had an easier time fixing this by refactoring the tokenization on placeholders as an explicit tokenization loop (i.e. iterating over characters). The logic should be easier to follow.

Do not normalize characters in placeholders during space tokenization

---

src/unicode/Unicode.cc

Reverts OpenNMT/Tokenizer#87
For unclear reasons, this was found to cause memory issues in a multi threaded context with ICU 57.1.

Revert "Use ICU for UTF8 to code point conversion"

---

src/SentencePiece.cc

This PR adds an include to `<stdexcept>`, which is required by `std::invalid_argument` and `std::runtime_error`. Visual Studio build fails without it when the `SentencePiece` library is found.

add missing include <stdexcept> required by std::invalid_argument

---

src/Tokenizer.cc

Special characters substitution was enabled for the "none" tokenization mode in f10e44ed. However, in SentencePiece compatibility mode (i.e. `Tokenizer("none", sp_model_path="...")`) we prefer to not alter the input text and let SentencePiece applies its own normalization.

Disable characters substitution in SentencePiece compatibility mode

---

include/onmt/BPELearner.h
include/onmt/SPMLearner.h
include/onmt/SubwordLearner.h
src/BPELearner.cc
src/SPMLearner.cc
src/SubwordLearner.cc

When using `SentencePieceLearner` without a tokenizer, the input text was just forwarded to an internal training file. However, for good integration in the OpenNMT tokenizer, we always need to ignore placeholders that could be present in the input text.

Always ignore placeholders when learning subword models

---

src/Tokenizer.cc

When using a tokenizer with `case_feature` during subword learning, the model will be trained on lowercase data. The same should be done when using the model.

Apply case_feature before subword encoding

---

src/CaseModifier.cc
src/unicode/Unicode.cc

This improves the performance for `--case_feature` and `--case_markup`.

Only convert the code point when the character should be lowercased

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py
include/onmt/BPELearner.h
include/onmt/SPMLearner.h
include/onmt/SubwordLearner.h
src/BPELearner.cc
src/SPMLearner.cc
src/SubwordLearner.cc

This is useful when tokenizing the data outside the learner.

Add public API to directly feed tokens to the subword learner

---

include/onmt/Tokenizer.h
src/Tokenizer.cc
test/test.cc

Take ownership of external subword encoder object by default

---

docs/options.md

fixed typo in `docs/options.md`:
`e.g. "2,000" is tokenized to "2 , 0000"`
to
`e.g. "2,000" is tokenized to "2 , 000",`

Typo in options.md

---

src/BPELearner.cc

Apply some performance and memory optimizations:
* Store bigrams in a shared container instead of duplicating and copying them
* Use unordered version of containers
* Remove some unused structures (e.g. `invstats`)
* Cleanup code: avoid copy by value, reserve vectors, avoid duplicated map lookup, etc.
The BPE model in output is unchanged.

Optimizations for BPE learning

---

cli/CMakeLists.txt

Without it being required, if it is not found, there will be no error from cmake, yet the project will not compile.

make Boost (program_options) required for CLI

---

test/CMakeLists.txt

By setting the googletest path based on current source directory (Tokenizer/test) and not setting it based on the top level source directory, Tokenizer will build as a submodule (e.g., as in CTranslate). Otherwise it looks for a non-existent directory (e.g., CTranslate/third_party/googletest).

set GoogleTest location based on current directory

---

cli/tokenize.cc

The `SubwordEncoder` pointer was deleted 2 times.

Fix subword encoder ownership in cli

---

src/Tokenizer.cc
test/test.cc

This prevents unwanted double spaces in the detokenized output.

Ignore empty tokens during detokenization

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py
include/onmt/CaseModifier.h
include/onmt/Token.h
include/onmt/Tokenizer.h
src/CaseModifier.cc
src/SubwordEncoder.cc
src/Tokenizer.cc
test/test.cc

* Case regions are serialization details and should not be properties of the class
* The index attribute was only used for the detokenization with ranges because it was convenient, but it should not be a property

Cleanup Token structure

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py

We only expose this flag in the Python API where it is the most useful.
Closes #158.

Add flag to return ranges on Unicode characters

---

CMakeLists.txt
bindings/python/Python.cc
cli/learn.cc
include/onmt/SPMLearner.h
include/onmt/SentencePieceLearner.h
src/SentencePieceLearner.cc

Keep previous header and symbol for backward compatibility.

Rename SPMLearner to SentencePieceLearner

---

bindings/python/Python.cc
include/onmt/SubwordLearner.h
include/onmt/Tokenizer.h
src/SubwordLearner.cc
src/Tokenizer.cc
test/test.cc

Subword encoders can now be set as shared_ptr so that client code can manage the caching instead.

Deprecate subword encoder caching

---

bindings/python/Python.cc
cli/tokenize.cc
docs/options.md
include/onmt/BPE.h
include/onmt/SentencePiece.h
include/onmt/SubwordEncoder.h
include/onmt/Tokenizer.h
src/BPE.cc
src/SentencePiece.cc
src/SubwordEncoder.cc
src/Tokenizer.cc
test/test.cc

This is required to make BPE vocabulary restriction work with spacer_annotate, joiner_new, etc.
This PR also make the subword encoder `const` when assigned to a tokenizer instance.

Declare tokenization options when setting a subword vocabulary

---

src/unicode/Unicode.cc
test/test.cc

Kangxi and Kanbun were listed in the now removed Alphabet.h header. However, they are not valid Unicode scripts aliases as defined
by ICU.
This PR adds a backward compatibility layer to correctly accept and identify those Unicode scipts.

Fix backward compatibility with Kangxi and Kanbun scripts

---

bindings/python/test/test.py
src/SentencePiece.cc

spacer_annotate is implicit for SentencePiece in "none" mode. But the code checked that the option was explicitly set before enabling
vocabulary restriction.

Fix SentencePiece vocab restriction without explicit spacer_annotate

---

bindings/python/test/test.py
src/SentencePiece.cc

It should work as long as spacer_annotate is used.

Do not require "none" mode for SentencePiece vocabulary restriction

---

include/onmt/BPE.h
include/onmt/Token.h
include/onmt/unicode/Unicode.h
src/BPE.cc
src/BPELearner.cc
src/Casing.cc
src/Tokenizer.cc
src/unicode/Unicode.cc
test/test.cc

The CharInfo structure is a string view with additional metadata. It
helps for performance as the input string in not copied and character
properties are resolved only once. It also helps for code clarity as
all character metadata are packed together.

Split characters into CharInfo objects

---

src/Tokenizer.cc
test/test.cc

The code was inside the block dealing with separator characters, but ZWJ is not in the separator Unicode category.
This could be considered a bug, but:
* the behavior was there for many versions (since we integrated ICU)
* the current output is reasonable, reversible, and does not cause vocabulary or learning issues
A future improvement could be to escape this kind of formatting characters.

Remove code dealing with Zero Width Joiner

---

include/onmt/unicode/Unicode.h
src/Tokenizer.cc
src/unicode/Unicode.cc
test/test.cc

We try to return a more specific script based on the previous letter properties.
Fixes #210.

Improve support of Common and Inherited script properties

---

bindings/python/test/test.py
src/Tokenizer.cc

A re-tokenization is required to get the complete and correct Token representation.

Fix Token deserialization for the general case

---

include/onmt/SentencePieceLearner.h
src/SentencePieceLearner.cc

It seems the following tow lines in src/SentencePieceLearner.cc are unnecessary, 
```cpp
_input_stream->flush();
_input_stream.reset(); 
```
actully, the var `_input_stream` is not used, but when training sentencepiece model from a file, these two lines will cause a coredump, so shall we just remove them~?

Adds pointer checking

---

bindings/python/tools/prepare_build_environment.sh

More recent ICU versions are available but the GCC version in manylinux1 is too old to compile them.

Update ICU to a newer version in Python wheels

---

bindings/python/pyonmttok/Python.cc

The wrapper should not assume that the C++ library is compiled against ICU.

Avoid using ICU in the Python wrapper

---

bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/test/test.py

This helper class should make it easy to create a tokenizer that is fully compatible with SentencePiece. In particular, the user does not need to think about the tokenization mode or other options that are not relevant to SentencePiece.

Add SentencePieceTokenizer to the Python module

---

docs/options.md
src/Tokenizer.cc

`case_markup` is currently not compatible with "none" and "space" tokenization modes.

Check tokenization mode when enabling case_markup

---

CMakeLists.txt
bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/test/test.py
cli/detokenize.cc
cli/tokenization_args.h
docs/options.md
include/onmt/Token.h
include/onmt/Tokenizer.h
include/onmt/unicode/Unicode.h
src/Casing.cc
src/Casing.h
src/Token.cc
src/Tokenizer.cc
src/unicode/Unicode.cc
test/test.cc

@panosk What do you think this? When the `lang` argument is set, we apply the locale-dependent uppercasing and titlecasing as provided by ICU (see the examples in the documentation below).
Related to #239.

Add lang argument and apply locale-dependent recasing

---

src/SubwordEncoder.cc
test/test.cc

Bug introduced in https://github.com/OpenNMT/Tokenizer/commit/520d034d6cd94f7a66360491a17cf1596a8e8fef.

Fix divergence with SentencePiece for detached leading spacers

---

src/SubwordEncoder.cc
test/test.cc

This is the same issue as https://github.com/OpenNMT/Tokenizer/commit/4056836634d1c827798b7658b6a5325ea187bafe but it happens when SentencePiece outputs a single subword. This case is rare unless SentencePiece is used as a subtokenizer.

Fix handling of detached spacers for single SentencePiece subword

---

src/Casing.cc
test/test.cc

The code did not consider that letters could not have any case information. This caused incorrect casing resolution when letters with and without case information are mixed.
This issue can happen when the sentence contains multiple scripts, e.g. Hiragana and Latin characters, so using the option `segment_alphabet_change` can also prevent this bug.

Fix casing resolution when some letters do not have case information

---

.github/workflows/ci.yml
bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/setup.py
bindings/python/test/test.py
bindings/python/tools/prepare_build_environment.sh

* Update manylinux to 2010
* Update pybind11 to 2.7.1
* Update ICU to 69.1
With manylinux2010 we can compile with C++17. This enables new features in pybind11 that makes the function signature clearer and improves the type checking. Here's an example from `help(pyonmttok.Tokenizer)`:
Before:
```text
|  detokenize(...)
|      detokenize(self: pyonmttok._ext.Tokenizer, tokens: list, features: object = None) -> str
```
After:
```text
|  detokenize(...)
|      detokenize(*args, **kwargs)
|      Overloaded function.
|      
|      1. detokenize(self: pyonmttok._ext.Tokenizer, tokens: List[str], features: Optional[List[List[str]]] = None) -> str
|      
|      2. detokenize(self: pyonmttok._ext.Tokenizer, tokens: List[pyonmttok._ext.Token]) -> str
```

Upgrade the Python wheels build environment

---

.github/workflows/ci.yml

Added linux aarch64 wheel support.
Related to: https://github.com/OpenNMT/Tokenizer/issues/273

Add aarch64 wheel build support

---

bindings/python/test/test.py
src/unicode/Unicode.cc

The list returned by `getISOLanguages` does not include deprecated language codes that are still accepted to create locales.

Improve lang validity check

---

README.md
bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/test/test.py

This simplifies the usage of the tokenizer when no features are returned (the common case).

Add basic Tokenizer.__call__ method

---

bindings/python/test/test.py
src/BPELearner.cc

This case does not happen with real data, but we should avoid hard crashes.

Fix BPELearner segfault when there is not a single pair of characters
