OpenNMT/Tokenizer

include/onmt/BPE.h
include/onmt/unicode/Unicode.h
src/BPE.cc
src/unicode/Unicode.cc
test/bpe-models/fr500
test/bpe-models/testcode

Load 'v3' bpe models trained by learn_bpe.lua to handle
- bpe_mode: prefix, suffix, none, both
- bpe_case_insensitive

 Add advanced bpe features

---

CHANGELOG.md
CMakeLists.txt
cli/tokenize.cc
include/onmt/Alphabet.h
include/onmt/Tokenizer.h
src/Alphabet.cc
src/Tokenizer.cc
test/test.cc

Add alphabet segmentation

---

CHANGELOG.md
bindings/python/Python.cc
bindings/python/README.md
cli/detokenize.cc
cli/tokenize.cc
include/onmt/Tokenizer.h
src/Tokenizer.cc
test/test.cc

to enable spacer as an alternative to joiner

add option "spacer_annotate"

---

CHANGELOG.md
include/onmt/BPE.h
src/BPE.cc

BPE optimization

---

CHANGELOG.md
CMakeLists.txt
README.md
cli/CMakeLists.txt
cli/learn.cc
include/onmt/AnnotatedToken.h
include/onmt/BPELearner.h
include/onmt/SubwordLearner.h
include/onmt/Tokenizer.h
src/AnnotatedToken.cc
src/BPE.cc
src/BPELearner.cc
src/SubwordLearner.cc
src/Tokenizer.cc

* Generic interface for subword learner
* cli interface `subword_learn`
* C++-implementation of BPE learner from https://github.com/rsennrich/subword-nmts - keeping same parameters

implement BPE learner (#17)

---

bindings/python/setup.py
bindings/python/tools/build_wheel_macosx.sh

macosx version of build wheel

---

cli/tokenize.cc
src/Tokenizer.cc

fix for when SentencePiece is missing

---

cli/tokenize.cc

These are the names used in the documentation.

Accept {bpe,sp}_model_path on the command line

---

bindings/python/Python.cc
bindings/python/test/test.py

Do not run Python code in wrapper destructor

---

docs/options.md
src/Tokenizer.cc
test/test.cc

Apply preserve_segmented_tokens in "none" tokenization mode

---

src/SentencePiece.cc
src/Tokenizer.cc
test/test.cc

Fix joiner annotation when SentencePiece returns isolated spacers

---

bindings/python/Python.cc
bindings/python/README.md
cli/tokenize.cc
docs/options.md
include/onmt/BPE.h
src/BPE.cc
test/test.cc

Add BPE dropout

---

docs/options.md
include/onmt/BPE.h
include/onmt/SubwordEncoder.h
src/BPE.cc
src/SubwordEncoder.cc
test/test.cc

Fix BPE vocab restriction when word has a leading or trailing joiner

---

bindings/python/Python.cc
bindings/python/README.md
bindings/python/test/test.py
cli/tokenize.cc
include/onmt/Tokenizer.h
src/BPE.cc
src/Tokenizer.cc
src/Utils.cc
src/Utils.h

Add set_random_seed function

---

src/Casing.cc
src/Casing.h
src/Tokenizer.cc
src/unicode/Unicode.cc

segment_case is about avoid tokens with mixed casing, so make that
clearer in the segmentation condition.

Implement segment_case based on token casing

---

src/Tokenizer.cc

Fix length check when unescaping

---

include/onmt/Tokenizer.h
src/Tokenizer.cc
test/test.cc

Fix space tokenization on protected sequences with spaces

---

include/onmt/SentencePieceLearner.h
src/SentencePieceLearner.cc

Sometimes developer do not want to remove their sentencepiece training data, so we can add an argument to control if remove sentencepiece-leaner input file or not

feat: Adds an argument to control if keep sentencepiece training data file.

---

CMakeLists.txt

Fix compiler flags for sentencepiece with MSVC

---

.github/workflows/ci.yml

This will catch basic compilation errors with MSVC.

Add a Windows compiltation job in the CI

---

bindings/python/README.md
bindings/python/pyonmttok/Python.cc
cli/tokenize.cc
include/onmt/ITokenizer.h
src/ITokenizer.cc

Add verbose flag to log tokenization progress

---

bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/test/test.py
include/onmt/BPE.h
include/onmt/ITokenizer.h
include/onmt/SentencePiece.h
include/onmt/SpaceTokenizer.h
include/onmt/SubwordEncoder.h
include/onmt/Tokenizer.h
src/BPE.cc
src/ITokenizer.cc
src/SentencePiece.cc
src/SpaceTokenizer.cc
src/SubwordEncoder.cc
src/Tokenizer.cc
test/test.cc

Add training flag to enable/disable subword regularization

---

.github/workflows/ci.yml
CMakeLists.txt
bindings/python/README.md
bindings/python/pyonmttok/__init__.py
bindings/python/setup.py
bindings/python/test/test.py
bindings/python/tools/prepare_build_environment_windows.sh

Build Python wheels for Windows

---

CHANGELOG.md
CMakeLists.txt
bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/pyonmttok/__init__.py
bindings/python/test/test.py
include/onmt/Vocab.h
src/Vocab.cc

Hi @vince62s, here's my proposal for a vocabulary API. There are helper functions to build the vocabulary from an iterator of lines or tokens. Can you take a look?
[Link to the rendered documentation](https://github.com/guillaumekln/Tokenizer/tree/vocab-api/bindings/python#vocabulary)
Closes #279.

Add a Vocab class and related functions

---

bindings/python/README.md
bindings/python/pyonmttok/Python.cc
bindings/python/test/test.py
include/onmt/Vocab.h

Hi @Zenglinxiao, can you check whether this addresses your needs? The counters of special tokens are set to 2^64-1.
Closes #286.

Expose token counters from Vocab class

---

cli/tokenization_args.h

Fix error when --segment_alphabet option is not set

---

.github/workflows/ci.yml
bindings/python/tools/prepare_build_environment.sh

Build ARM64 wheels for macOS

---

CMakeLists.txt

Fix static compilation

---

bindings/python/test/test.py
include/onmt/Tokenizer.h
src/BPE.cc
src/Tokenizer.cc

This issue was mentioned in #313.

Consider escaped characters as single characters in BPE
